#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Full local dev environment bootstrap
# Usage: ./scripts/dev-setup.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

echo "╔══════════════════════════════════════════════════════════╗"
echo "║       Growth Engine Cinema — Dev Setup                  ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Check prerequisites ──────────────────────────────────────────────────────
for cmd in node npm docker docker-compose; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "✗ $cmd is required but not installed."
    exit 1
  fi
done

NODE_MAJOR=$(node -e 'process.stdout.write(process.version.replace("v","").split(".")[0])')
if [[ "$NODE_MAJOR" -lt 20 ]]; then
  echo "✗ Node.js 20+ required (found v${NODE_MAJOR})"
  exit 1
fi

echo "✓ Prerequisites OK (Node $(node -v))"

# ── Create .env.local from example ──────────────────────────────────────────
if [[ ! -f ".env.local" ]]; then
  cp .env.example .env.local
  cat >> .env.local << 'EOF'

# ── Docker local overrides (auto-generated by dev-setup.sh) ──────────────────
DATABASE_URL=postgresql://cinema:cinema_dev@localhost:5432/cinema
REDIS_URL=redis://:cinema_dev@localhost:6379
R2_ACCOUNT_ID=local
R2_ACCESS_KEY_ID=cinema
R2_SECRET_ACCESS_KEY=cinema_dev_secret
R2_BUCKET_NAME=cinema-media
R2_PUBLIC_URL=http://localhost:9000/cinema-media
WORKER_HEALTH_TOKEN=local-health-token
CRON_SECRET=local-cron-secret
EOF
  echo "✓ Created .env.local (fill in API keys for AI features)"
else
  echo "✓ .env.local already exists"
fi

# ── Start Docker services ────────────────────────────────────────────────────
echo ""
echo "→ Starting Docker services (Postgres, Redis, MinIO)…"
docker compose up -d postgres redis minio minio-init
echo "→ Waiting for services to be healthy…"
sleep 5

# ── Install dependencies ─────────────────────────────────────────────────────
echo "→ Installing npm dependencies…"
npm install

# ── Database setup ───────────────────────────────────────────────────────────
echo "→ Generating Prisma client…"
npx prisma generate

echo "→ Running migrations…"
npx prisma migrate dev --name init 2>/dev/null || npx prisma migrate deploy

echo "→ Seeding database…"
npx tsx scripts/seed.ts

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  ✓  Dev environment ready!                              ║"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║  Start web app:  npm run dev                            ║"
echo "║  Start workers:  npm run workers                        ║"
echo "║  Postgres UI:    http://localhost:5050                  ║"
echo "║    (run: docker compose --profile debug up -d pgadmin) ║"
echo "║  MinIO console:  http://localhost:9001                  ║"
echo "║    login: cinema / cinema_dev_secret                   ║"
echo "║  Redis UI:       docker compose --profile debug up -d  ║"
echo "╚══════════════════════════════════════════════════════════╝"
